### ISSUE TITLE
Add support for use in browser

### ISSUE THREAD

**Issue by treyhunner** [SonicHedgehog/detect-character-encoding#4]
If this worked client-side, the [File API](https://www.w3.org/TR/FileAPI/) could be used to read a file locally and detect everything locally which would avoid the need to upload anything to a server.

It looks like this relies on C++ code. Any chance this could be turned into a fully JavaScript-powered library in the future?

**Comment by sonicdoe** [comment]
My main goal with this library was to take advantage of [ICU](http://site.icu-project.org) because it seems to be the most widely tested charset detector.

I don’t think there’s an easy way to make ICU’s detector work client-side, so I’d suggest using a simpler charset detector, [such as your own](https://github.com/treyhunner/detect-charset). Would this work for you?

**Comment by treyhunner** [comment]
I understand. Mine isn't sophisticated enough. :disappointed: 

FYI I found [jschardet](https://github.com/aadsm/jschardet) which claims to be a port of Python's chardet which also detects character encodings. I haven't played with it yet but it should work in browser. Thanks!
